#!/bin/bash

sito="1.1.1.1"
Nc=10 #Numero di verifice prima dell'riavvio
A1=1800 #Tempo di attesa per la verifica della connessione internet 
A2=10 #Tempo di attesa tra un ping e l'altro prima del riavvio dell'interfaccia
A3=60 #Tempo di attesa dopo il riavvio dell'interfaccia
Pc=0

#Questa funzione verifica con la periodicità A1 la presenza di connessione di rete

function ver_line() 
{
p=1
while [ $p == 1 ]
do 
	ping -c 1 $sito && p=1 || p=0
	sleep $A1
done
ver_lin_forz
}

#Questa funzione verifica con la periodicità A2 la presenza di connessione di rete per Nc volte prima di effettuare il riavvio

function ver_lin_forz()
{
p2=0
while [ $Pc -le $Nc ]
do
ping -c 1 $sito && p2=0 || p2=1
		if [ $p2 == 0 ]
		then
			ver_line
			brake
		fi
			Pc=$(( $Pc + $p2 ))
			sleep $A2
done
	Pc=0
	reboot_interface

}

function reboot_interface()
{
	#Riavvio interfaccia
	sleep $A3
	ver_line
}


ver_line
